Exercise 3
angeline-tech/DevOps-Course-Starter pull request #5
Opened 2021-01-25 17:38 UTC by angeline-tech

Hi. Acceptance Tests work when I run them using the test explorer. When I try to run them using poetry I get a JSON decoder error. Not too sure what's going on.

2021-02-08 09:44 UTC, JackMead requested changes
Nice work, I've left a few thoughts on things we could adjust but the main thing is getting the tests working with the instructions from the readme. I've left details in the comments on the PR, but the main thing is ensuring the environment variables are loaded, and that it happens _before_ we try to process them into authentication details 

If you have any questions, feel free to reach out on slack or book in a support call

2021-02-08 09:44 UTC, JackMead commented on tests/acceptance/test_e2e.py
> +    board = create_board()
The reason pytest is currently failing this test is because we haven't loaded the environment variables before this step - your test runner may do this automatically, but for running directly we should explicitly load the `.env` file (similarly to the integration test).

This will need to be combined with a slightly different approach to setting the auth - discussed elsewhere

2021-02-08 09:44 UTC, JackMead commented on tests/acceptance/test_e2e.py
> +    time.sleep(1)
Not vital, but ideally we wouldn't need these explicit sleep calls - selenium should automatically wait for the element if it's not immediately present. It looks like they're required so that our asserts are made at the right moment, but we might be better off relying on facts that selenium will automatically wait for, like just checking an expected element has appeared.

2021-02-08 09:44 UTC, JackMead commented on tests/utils/card_utils.py
> +from todo_app.data.Card import Card
Nice separation using this file

2021-02-08 09:44 UTC, JackMead commented on todo_app/app.py
> +def fake():
Do we still need this?

2021-02-08 09:44 UTC, JackMead commented on todo_app/flask_config.py
> +    # TODO: Fix this? Integration tests won't run
The reason for this is similar to that in the `auth` case. One solution would be to change this from a class property (which is set at import time, so before the integration test has loaded environment variables) to object properties set in the constructor. However, we no longer need this since we moved to trello, so possibly easiest is getting rid of the SECRET_KEY entirely!

2021-02-08 09:44 UTC, JackMead commented on todo_app/service/trello_service.py
>      url = trello + "lists/" + os.getenv(list_id) + "/cards" + auth
The other main problem with running your tests from the command line, is that this `auth` string is defined at import time, so before your test has had a chance to load the dotenv file in. There are a few ways round this, including:
* Turning this service into a class, where the auth string is set in the constructor
* Replacing the string with a function that returns the same string (so that the string is put together when needed, rather than in advance)

2021-02-08 09:44 UTC, JackMead commented on README.md
> +## Runnning Tests
Good job on adding some docs! Could we also mention any prerequisites, e.g. geckodriver, and firefox? :)

2021-02-22 19:23 UTC, angeline-tech commented on todo_app/service/trello_service.py
>      url = trello + "lists/" + os.getenv(list_id) + "/cards" + auth
Added an auth() function to construct the auth string

2021-02-22 19:23 UTC, angeline-tech commented on todo_app/flask_config.py
> +    # TODO: Fix this? Integration tests won't run
Removed this

2021-02-22 19:24 UTC, angeline-tech commented on tests/acceptance/test_e2e.py
> +    time.sleep(1)
Tried to remove the sleep calls but then it wouldn't wait for the elements to appear it would just throw an element not found exception. Weirdly even when I tried to look for elements (i.e. get the array) it would still throw that exception

2021-02-22 19:24 UTC, merged

2021-03-08 17:32 UTC, hugh-emerson commented on README.md
> +* Add the path to the GeckoDriver Executable your `.env` file (`GECKO_PATH`)
This seems like overcomplicating the setup. The default behaviour (`webdriver.Firefox()`)  is to check both PATH and the project root directory, which should be sufficient. You can .gitignore geckodriver to let people just stick it in the project folder. And then either:
- Forget about GECKO_PATH
- Or keep it as optional env var by using it to append to `os.environ['PATH']` before you run `Firefox()`.

2021-03-08 17:32 UTC, hugh-emerson commented on .env.test
> +GECKO_PATH=PATH+TO+GECKO
.env.test surely doesn't need GECKO_PATH - only the selenium tests should use it and those should be using the real .env

2021-03-08 17:35 UTC, hugh-emerson commented on tests/integration/test_app.py
> +    # monkeypatch.setattr(trello_service,"fetch_updated_cards",empty_array)
Delete commented out code

2021-03-08 17:36 UTC, hugh-emerson commented on tests/integration/test_app.py
> +    monkeypatch.setattr(trello_service,"request_cards",raw_cards)
You should be patching as little as possible in an integration test. What you've written is more of a unit test of app.py.

An integration test is supposed to test all of your code working together, so you only patch `requests.get`

2021-03-08 17:38 UTC, hugh-emerson commented on todo_app/app.py
> +    return redirect('/?show_older=true') if show_older else redirect('/?show_older=false')
The way you've done this means you can't set both the `show_older` and `ascending` query parameters?

2021-03-08 17:45 UTC, hugh-emerson commented on todo_app/service/trello_service.py
> +#         self._auth = auth_string
Delete commented out code